### ISSUE TITLE
Putting links to spaces on slides 

### ISSUE THREAD

**Issue by audreymutswiri** [diging/virtual-spaces-2.0#164]
Would it be possible to put links to spaces on slides? 

The idea I have for the layout is as follows, 

On the home page, there is a link icon to a module called, "meet the team" ----once I click on that icon it should take me to the slides with pictures, names, and roles of individual team members. 
So now on each of the slides if possible there should be a link to that team member's space where their profile and projects can be found.

**Comment by jdamerow** [comment]
https://diging.atlassian.net/browse/VSPC-171
